spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/USER FOR LOGIN DETAILS
spring.datasource.username=postgres
spring.datasource.password=Kiran@c5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

